/**
 * Expose Filament's MCP tool surface to the OpenClaw agent, in parity with
 * the Python `filament-hermes` plugin's *intent* (registering the server's
 * tools as agent tools) but NOT its mechanism.
 *
 * ## Registration is synchronous, from a static schema snapshot
 *
 * OpenClaw's plugin entry point is synchronous
 * (`OpenClawPluginDefinition.register?: (api: OpenClawPluginApi) => void` —
 * no `Promise` return, see `node_modules/openclaw/dist/types-DaHgOqFX.d.ts`),
 * and a session's toolset is resolved once, early, from whatever the
 * registry holds at that point — a live `2026.9.5` gateway log confirms this
 * empirically (`plans/openclaw/tools-not-visible-diagnosis.md`, §5): a
 * registration made *after* `register(api)` returns (as this module
 * previously did, from `startAccount` post-connect) is technically honored
 * by the mutable process-wide registry, but arrives too late for a harness
 * that already snapshotted its tool list before that write landed (observed
 * with the Codex app-server harness's `tool_search`/deferred-tools path —
 * see that doc for the mechanism). Registering every tool synchronously
 * inside `register(api)`, from a schema snapshotted ahead of time rather
 * than fetched live, removes the race entirely: by the time any session
 * resolves its toolset, every `filament_*` tool is already in the registry.
 *
 * The snapshot (`src/filament-tools.snapshot.json`) is generated by
 * `npm run snapshot:tools` (`scripts/snapshot-tools.mjs`) against a live
 * server's `tools/list`, or — when no bearer is available to hit the live
 * endpoint — read straight out of the `synapse` source's `ToolDef` registry
 * (see that script's header). Because the schema is no longer fetched at
 * connect time, a tool's `execute()` instead resolves the *connection*
 * lazily, through a module-level holder (`setFilamentClient`/
 * `getFilamentClient`) that `src/channel.ts`'s `startAccount` sets once
 * `runConnect` resolves and clears on abort/fatal — the registration itself
 * no longer depends on being connected.
 *
 * ## Drift is logged, not auto-registered, at connect time
 *
 * After connect, `checkFilamentToolDrift` still calls `tools/list` once and
 * logs any mismatch between what the live server advertises and what the
 * snapshot has — the only remaining place that live catalog is consulted.
 * It never registers anything at runtime any more; a real drift needs a
 * human to re-run `npm run snapshot:tools` and review the diff (same
 * reasoning as `KNOWN_TOOL_NAMES` below).
 *
 * ## What gets registered
 *
 * Every tool in the snapshot, which itself already excludes:
 *   - `poll_work` — the poll loop (`src/poll-work.ts`) owns this call
 *     exclusively; the agent must never call it directly.
 *   - `register_push_token` / `list_push_tokens` — harness plumbing for an
 *     FCM-based transport. This plugin uses `poll_work`, not FCM, so these
 *     tools have no push token to register and would just confuse the
 *     model. Hermes excludes the FCM-specific equivalent of these for the
 *     identical reason (see its `BLOCKED_TOOLS`); this is the one place we
 *     depart from a literal "expose everything but poll_work" reading of
 *     the parity goal, and it is a considered call, not an oversight.
 *
 * `openclaw.plugin.json`'s `contracts.tools` must list every name the
 * snapshot can register (the manifest doc: "Runtime `api.registerTool(...)`
 * registrations must match `contracts.tools`") — a unit test asserts the two
 * stay in sync, so drift fails CI rather than surfacing at runtime.
 *
 * ## Authorization tiers
 *
 * Each registered (non-excluded) tool falls into one of three tiers,
 * decided per-call inside `execute()` (OpenClaw's `registerTool` options
 * are just `{name, names, optional}` — no channel/session scoping exists to
 * do this at registration time; see `authorizeToolCall` below):
 *
 *   - **read** — `annotations.readOnlyHint === true` in the live schema.
 *     Always allowed, from any turn.
 *   - **ring0** — `set_profile`: Filament's own tool declares this
 *     `ungated_reason="agent self-configuration, not channel content"`
 *     (synapse `tools_config.py`), and `filament-hermes/docs/
 *     agent-boundaries.md` §5 names exactly this class ("tools that change
 *     the agent are Ring 0 and principal-only") as backchannel/principal-only.
 *     Allowed only during a turn dispatched from an `is_backchannel` work
 *     item.
 *   - **write** — everything else with `readOnlyHint !== true`. Allowed
 *     from any turn this plugin's own poll loop dispatched (backchannel or
 *     group), matching Hermes' default posture for its non-Ring-0 tools.
 *
 * A tool whose `readOnlyHint` is missing or not a boolean (a malformed or
 * future schema shape) is treated as `ring0` — the strictest tier — rather
 * than guessed as read or ordinary write.
 *
 * ## One Filament account per OpenClaw agent
 *
 * Each tool is registered as a *factory* (`OpenClawPluginToolFactory`),
 * which OpenClaw calls with the agent/session it is building a toolset for
 * (`agentId`, `messageChannel`, `agentAccountId`, `config`). The factory
 * resolves which Filament channel account that agent is bound to
 * (`resolveToolAccountId`, src/accounts.ts) and closes over it, so a tool
 * call always uses the bearer of *its own* agent's account; an agent with no
 * Filament account gets no `filament_*` tools at all. Names stay static, so
 * `contracts.tools` still lists them exactly.
 *
 * ## The turn-tracking limitation
 *
 * `execute()`'s `ctx: ExtensionContext` carries no session/channel/peer
 * identity, so authorization uses a per-account "current turn" slot
 * (`beginFilamentTurn`/`endFilamentTurn`), set/cleared by `src/channel.ts`
 * around each `dispatchWorkItemTurn` call. Two Filament accounts never share
 * a slot, and each account's poll loop is sequential. What remains: if the
 * *same* OpenClaw agent runs a turn on a different channel (Telegram, …)
 * while its Filament turn is in flight, that turn inherits Filament-turn
 * authorization for the overlap. Accepted for this PoC.
 */
import { DEFAULT_ACCOUNT_ID, resolveToolAccountId, type ToolAccountContext } from "./accounts.js";
import type {
  CallOptions,
  ListToolsResult,
  McpToolDescriptor,
  ToolCallResult,
} from "./mcp-client.js";
// The reviewed schema snapshot (see the module docstring's "Registration is
// synchronous, from a static schema snapshot"). Regenerate with
// `npm run snapshot:tools`.
import rawToolSnapshot from "./filament-tools.snapshot.json" with { type: "json" };

/** Tool name prefix this plugin registers under (stock-plugin convention —
 *  see e.g. `discord_*`/`telegram_*` tool names in the installed OpenClaw's
 *  bundled channel-adjacent tool plugins). */
export const TOOL_NAME_PREFIX = "filament_";

/** One entry in `src/filament-tools.snapshot.json` — a `McpToolDescriptor`
 *  minus the fields the snapshot doesn't carry (see the generator scripts'
 *  headers for why `annotations` is kept despite the minimal
 *  `{name, description, inputSchema}` spec). */
export interface SnapshotToolDescriptor {
  name: string;
  description: string;
  inputSchema: unknown;
  annotations?: { readOnlyHint?: boolean; [key: string]: unknown };
}

/** The static, reviewed tool schema snapshot, sorted by name. Every tool
 *  this plugin registers comes from this array — see the module docstring. */
export const TOOL_SNAPSHOT: readonly SnapshotToolDescriptor[] =
  rawToolSnapshot as SnapshotToolDescriptor[];

/**
 * The reviewed snapshot of Filament MCP tool names this plugin may expose,
 * unprefixed (as the server names them), derived from `TOOL_SNAPSHOT`. Must
 * stay in sync with `openclaw.plugin.json`'s `contracts.tools` (which
 * carries the same names, prefixed) — a unit test asserts this — see the
 * module docstring's "What gets registered".
 */
export const KNOWN_TOOL_NAMES: readonly string[] = TOOL_SNAPSHOT.map((t) => t.name);

/** Tools always excluded from the snapshot, with why (see module docstring).
 *  Also used by `logToolDrift` so these expected exclusions never show up as
 *  "drift" against a live server that (correctly) still advertises them. */
const EXCLUDED_TOOLS: ReadonlyMap<string, string> = new Map([
  ["poll_work", "the poll loop owns this call exclusively"],
  ["register_push_token", "FCM harness plumbing; this transport is poll_work, not FCM"],
  ["list_push_tokens", "FCM harness plumbing; this transport is poll_work, not FCM"],
]);

/** Ring-0 (principal/backchannel-only) tool names — see module docstring. */
const RING0_TOOL_NAMES: ReadonlySet<string> = new Set(["set_profile"]);

export type ToolTier = "read" | "ring0" | "write";

/** Classify a live tool descriptor into an authorization tier. Exported for tests. */
export function classifyToolTier(descriptor: McpToolDescriptor): ToolTier {
  if (RING0_TOOL_NAMES.has(descriptor.name)) return "ring0";
  const readOnly = descriptor.annotations?.readOnlyHint;
  if (readOnly === true) return "read";
  if (readOnly === false) return "write";
  // Missing/malformed annotations: fail closed to the strictest tier.
  return "ring0";
}

// ── Turn tracking (see module docstring's "turn-tracking limitation") ──────

interface FilamentTurnState {
  backchannel: boolean;
}

// One slot per channel account: two Filament agents on one gateway dispatch
// turns independently, and each account's poll loop is itself sequential.
const activeFilamentTurns = new Map<string, FilamentTurnState>();

/** Call before dispatching a Filament work-item turn on `accountId`. */
export function beginFilamentTurn(isBackchannel: boolean, accountId = DEFAULT_ACCOUNT_ID): void {
  activeFilamentTurns.set(accountId, { backchannel: isBackchannel });
}

/** Call after that account's work-item turn finishes (success or failure). */
export function endFilamentTurn(accountId = DEFAULT_ACCOUNT_ID): void {
  activeFilamentTurns.delete(accountId);
}

/** Test-only accessor. */
export function _getActiveFilamentTurnForTest(
  accountId = DEFAULT_ACCOUNT_ID,
): FilamentTurnState | null {
  return activeFilamentTurns.get(accountId) ?? null;
}

export interface AuthorizationResult {
  ok: boolean;
  reason?: string;
}

/** Decide whether a call in tier `tier` may run now on `accountId`. Exported for tests. */
export function authorizeToolCall(
  tier: ToolTier,
  accountId = DEFAULT_ACCOUNT_ID,
): AuthorizationResult {
  if (tier === "read") return { ok: true };
  const activeFilamentTurn = activeFilamentTurns.get(accountId);
  if (!activeFilamentTurn) {
    return {
      ok: false,
      reason: "no active Filament turn (not dispatched by this plugin's poll loop)",
    };
  }
  if (tier === "ring0" && !activeFilamentTurn.backchannel) {
    return {
      ok: false,
      reason: "principal-only tool; the active turn did not originate from the backchannel",
    };
  }
  return { ok: true };
}

// ── Client + registration ───────────────────────────────────────────────

/** Minimal client surface a tool needs (matches FilamentMcpClient.callTool). */
export interface FilamentToolClient {
  callTool(
    name: string,
    args?: Record<string, unknown>,
    opts?: CallOptions,
  ): Promise<ToolCallResult>;
}

/** Resolves an account's live client, or null when it is not currently connected. */
export type GetFilamentClient = (accountId: string) => FilamentToolClient | null;

// ── Connection holder ───────────────────────────────────────────────────
//
// Tools are now registered synchronously in `register(api)`, before any
// connection exists. A tool's `execute()` therefore can't close over the
// connection directly (there isn't one yet); it resolves it lazily through
// this module-level holder instead. `src/channel.ts`'s `startAccount` calls
// `setFilamentClient(connection.client)` once `runConnect` resolves, and
// `setFilamentClient(null)` on abort/fatal/stop, so a tool call made outside
// that window throws a clear "not connected yet" error rather than silently
// hanging or reaching a stale client.

const filamentClients = new Map<string, FilamentToolClient>();

/** Set (or clear, with `null`) the live connection an account's tools call through. */
export function setFilamentClient(
  client: FilamentToolClient | null,
  accountId = DEFAULT_ACCOUNT_ID,
): void {
  if (client) filamentClients.set(accountId, client);
  else filamentClients.delete(accountId);
}

/** The default `GetFilamentClient` used by tools registered at plugin load. */
export function getFilamentClient(accountId = DEFAULT_ACCOUNT_ID): FilamentToolClient | null {
  return filamentClients.get(accountId) ?? null;
}

/**
 * Loose structural view of the plugin tool-registration surface (see
 * `src/channel.ts`'s `FilamentChannelApi` for the established precedent of
 * this pattern in this repo): the concrete `OpenClawPluginApi`/
 * `ToolDefinition<TParams extends TSchema>` types require a TypeBox schema
 * object, and `typebox` is only reachable inside `openclaw`'s own nested
 * `node_modules` (not a resolvable import from this package) — see the
 * module docstring. A plain JSON Schema object (exactly what Filament's
 * `tools/list` already returns) is passed through as `parameters` instead.
 */
export interface FilamentToolsApi {
  registerTool(
    factory: (ctx: ToolAccountContext) => FilamentAgentTool | null,
    opts: { names: string[] },
  ): void;
  /** Plugin config at load time; the account fallback when a ctx carries no config. */
  pluginConfig?: unknown;
}

/** Picks the Filament account a tool call belongs to; see src/accounts.ts. */
export type ResolveToolAccount = (ctx: ToolAccountContext) => string | null;

interface FilamentToolResult {
  content: Array<{ type: "text"; text: string }>;
  details: unknown;
}

export interface FilamentAgentTool {
  name: string;
  label: string;
  description: string;
  parameters: unknown;
  execute: (
    toolCallId: string,
    params: Record<string, unknown>,
    signal: AbortSignal | undefined,
    onUpdate: unknown,
    ctx: unknown,
  ) => Promise<FilamentToolResult>;
}

const FALLBACK_PARAMETERS = { type: "object", properties: {}, additionalProperties: true } as const;

function toLabel(name: string): string {
  return name
    .split("_")
    .map((w) => (w.length > 0 ? w[0]!.toUpperCase() + w.slice(1) : w))
    .join(" ");
}

/** Build the `execute` closure for one tool, proxying through the live connection. */
function makeExecute(
  toolName: string,
  tier: ToolTier,
  accountId: string,
  getClient: GetFilamentClient,
  log: (message: string) => void,
): FilamentAgentTool["execute"] {
  const qualifiedName = `${TOOL_NAME_PREFIX}${toolName}`;
  return async (_toolCallId, params) => {
    const authz = authorizeToolCall(tier, accountId);
    if (!authz.ok) {
      log(`filament-tools: ${qualifiedName} denied (account ${accountId})`);
      throw new Error(`${qualifiedName}: denied — ${authz.reason}`);
    }
    const client = getClient(accountId);
    if (!client) {
      log(`filament-tools: ${qualifiedName} failed`);
      throw new Error(`${qualifiedName}: Filament is not connected yet`);
    }
    let result: ToolCallResult;
    try {
      result = await client.callTool(toolName, params);
    } catch (error) {
      log(`filament-tools: ${qualifiedName} failed`);
      throw new Error(`${qualifiedName}: call failed — ${String(error)}`);
    }
    if (!result.ok) {
      log(`filament-tools: ${qualifiedName} failed`);
      throw new Error(
        `${qualifiedName}: ${result.kind ?? "error"} — ${result.error?.message ?? "unknown error"}`,
      );
    }
    log(`filament-tools: ${qualifiedName} ok`);
    return {
      content: [{ type: "text", text: JSON.stringify(result.data ?? null) }],
      details: result.data,
    };
  };
}

export interface RegisterFilamentToolsResult {
  registered: string[];
  skipped: Array<{ name: string; reason: string }>;
}

/**
 * Register every tool in `TOOL_SNAPSHOT` synchronously. Call this from
 * `register(api)` — see the module docstring's "Registration is
 * synchronous, from a static schema snapshot". `getClient` is consulted
 * fresh on every *call* (not at registration time), so a tool works as soon
 * as `setFilamentClient` is set and degrades cleanly if the connection later
 * drops, without needing to be unregistered.
 */
export function registerFilamentToolsFromSnapshot(
  api: FilamentToolsApi,
  getClient: GetFilamentClient,
  log: (message: string) => void,
  resolveAccount: ResolveToolAccount = (ctx) => resolveToolAccountId(ctx, api.pluginConfig),
): RegisterFilamentToolsResult {
  const registered: string[] = [];

  for (const descriptor of TOOL_SNAPSHOT) {
    const tier = classifyToolTier(descriptor as McpToolDescriptor);
    const qualifiedName = `${TOOL_NAME_PREFIX}${descriptor.name}`;
    // A factory, not a tool: OpenClaw builds it per agent/session, so the
    // tool is bound to that agent's Filament account — and absent (null) for
    // an agent with none, rather than calling through someone else's bearer.
    api.registerTool(
      (ctx) => {
        const accountId = resolveAccount(ctx ?? {});
        if (!accountId) return null;
        return {
          name: qualifiedName,
          label: toLabel(descriptor.name),
          description: descriptor.description || descriptor.name,
          parameters: descriptor.inputSchema ?? FALLBACK_PARAMETERS,
          execute: makeExecute(descriptor.name, tier, accountId, getClient, log),
        };
      },
      { names: [qualifiedName] },
    );
    registered.push(qualifiedName);
  }

  log(`filament-tools: registered ${registered.length} tool(s) from snapshot`);
  return { registered, skipped: [] };
}

/**
 * Compare a live `tools/list` response against `TOOL_SNAPSHOT` and log any
 * mismatch — never registers or unregisters anything (see the module
 * docstring's "Drift is logged, not auto-registered, at connect time").
 * Exported separately from `checkFilamentToolDrift` for tests that want to
 * supply the live tool list directly rather than a fake client.
 */
export function logToolDrift(liveTools: McpToolDescriptor[], log: (message: string) => void): void {
  const snapshotNames = new Set(TOOL_SNAPSHOT.map((t) => t.name));
  const liveNames = new Set(
    liveTools.map((t) => t.name).filter((name) => !EXCLUDED_TOOLS.has(name)),
  );

  const extra = [...liveNames].filter((name) => !snapshotNames.has(name)).sort();
  const missing = [...snapshotNames].filter((name) => !liveNames.has(name)).sort();

  if (extra.length > 0) {
    log(
      `filament-tools: server exposes ${extra.length} tool(s) not in the snapshot: ${extra.join(", ")}`,
    );
  }
  if (missing.length > 0) {
    log(
      `filament-tools: snapshot has ${missing.length} tool(s) the server no longer serves: ${missing.join(", ")}`,
    );
  }
  if (extra.length === 0 && missing.length === 0) {
    log("filament-tools: snapshot matches the live server's tool surface");
  }
}

/**
 * Fetch the live tool catalog and log any drift against `TOOL_SNAPSHOT`.
 * Call this once after connect (see `src/channel.ts`). Best-effort: a
 * failed `tools/list` call is logged and treated as "nothing to check"
 * rather than thrown — the tool surface itself is already registered and
 * working regardless of whether this diagnostic call succeeds.
 */
export async function checkFilamentToolDrift(
  client: { listTools(opts?: CallOptions): Promise<ListToolsResult> },
  log: (message: string) => void,
): Promise<void> {
  const result = await client.listTools();
  if (!result.ok || !result.tools) {
    log(
      `filament-tools: drift check skipped (tools/list failed: ${result.kind ?? "?"}: ${result.error?.message ?? "?"})`,
    );
    return;
  }
  logToolDrift(result.tools, log);
}
